version: '3.9'

services:
  pgdatabase:
    image: postgres:16.3
    container_name: pgdatabase
    restart: unless-stopped
    environment:
      POSTGRES_DB: udb
      POSTGRES_USER: udbuser
      POSTGRES_PASSWORD: udbpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  