direction: right

departments: {
    shape: sql_table

    department_id: bigint {constraint: primary_key}
    department_title: vachar(255)
    department_description: text
}

students: {
    shape: sql_table

    student_id: bigint {constraint: primary_key}
    major_id: bigint {constraint: foreign_key}
    student_code: vachar(20) {constraint: unique}
    student_email: vachar(100) {constraint: unique}
    student_first_name: vachar(255)
    student_last_name: vachar(255)
    student_birthdate: date
    enrollment_date: date
}

professors: {
    shape: sql_table

    professor_sin: vachar(9) {constraint: primary_key}
    department_id: bigint {constraint: foreign_key}
    professor_email: vachar(100) {constraint: unique}
    professor_first_name: vachar(255)
    professor_last_name: vachar(255)
    professor_birthdate: date
}

majors: {
    shape: sql_table
  
    major_id: bigint {constraint: primary_key}
    major_code: vachar(20) {constraint: unique}
    department_id: bigint {constraint: foreign_key}
    major_title: vachar(255)
    major_description: text
}

major_courses: {
    shape: sql_table

    major_course_id: bigint {constraint: primary_key}
    course_id: bigint {constraint: foreign_key}
    major_id: bigint {constraint: foreign_key}
}

courses: {
    shape: sql_table
  
    course_id: bigint {constraint: primary_key}
    prerequisite_course_id: array
    course_code: vachar(20) {constraint: unique}
    course_title: vachar(255)
    course_description: text
    course_type: vachar {constraint: enum(General, Fundamental, Specialized)}
    course_required: boolean {constraint: default: false}
}

semesters: {
    shape: sql_table

    semester_id: bigint {constraint: primary_key}
    semester_name: varchar(100)
    start_date: date
    end_date: date
}

sections: {
    shape: sql_table
  
    section_id: bigint {constraint: primary_key}
    major_course_id: bigint {constraint: foreign_key}
    semester_id: bigint {constraint: foreign_key}
    professor_sin: varchar(9) {constraint: foreign_key}
    max_capacity: int
}

timetables: {
    shape: sql_table
  
    timetables_id: bigint {constraint: primary_key}
    section_id: bigint {constraint: foreign_key}
    room: vachar(20)
    status: vachar {constraint: enum(Scheduled, Cancelled, Completed)}
    schedule_time: datetime
}

student_sections: {
    shape: sql_table
  
    student_section_id: bigint {constraint: primary_key}
    student_id: bigint {constraint: foreign_key}
    section_id: bigint {constraint: foreign_key}
    enrollment_date: date
    score: float
}

departments.department_id --> majors.department_id {
  label: "1:N"
  style.stroke-width: 2
}

departments.department_id --> professors.department_id {
  label: "1:N"
  style.stroke-width: 2
}

majors.major_id --> students.major_id {
  label: "1:N"
  style.stroke-width: 2
}

majors.major_id --> major_courses.major_id {
  label: "1:N"
  style.stroke-width: 2
}

courses.course_id --> major_courses.course_id {
  label: "1:N"
  style.stroke-width: 2
}

semesters.semester_id --> sections.semester_id {
  label: "1:N"
  style.stroke-width: 2
}

major_courses.major_course_id --> sections.major_course_id {
  label: "1:N"
  style.stroke-width: 2
}

professors.professor_sin --> sections.professor_sin {
  label: "1:N"
  style.stroke-width: 2
}

sections.section_id --> student_sections.section_id {
  label: "1:N"
  style.stroke-width: 2
}

students.student_id --> student_sections.student_id {
  label: "1:N"
  style.stroke-width: 2
}

sections.section_id --> timetables.section_id {
  label: "1:N"
  style.stroke-width: 2
}

# scores: {
#     shape: sql_table
#     score_id: bigint {constraint: primary_key}
#     student_id: bigint {constraint: foreign_key}
#     course_id: bigint
#     score: float
# }

# students.student_id --> scores.student_id {
#   label: "1:N"
#   style.stroke-width: 2
# }

# course_attributes: {
#     shape: sql_table
  
#     course_attribute_id: bigint {constraint: primary_key}
#     course_id: bigint {constraint: foreign_key}
#     major_id: bigint
#     required: boolean
#     credit: int
# }

# courses.course_id --> course_attributes.course_id {
#   label: "1: N"
#   style.stroke-width: 2
# }

legend: {
  shape: text
  label: |md
    ## Database Relationship
    ### 1:N Relationships
    - **Departments → Major** (1:N): One department has many major
    - **Departments → Professors** (1:N): One department has many professors
    - **Majors → Students** (1:N): One major has many student
    - **Sections → Timetables** (1:N): Each section has many lessons
    - **Semesters → Sections** (1:N): There are many classes each semester.
    - **Major_courses → Sections** (1:N): Each major_course will have many classes.
    - **Professors → Sections** (1:N): Each professor is in charge of many class.

    ### M:N Relationships
    - **Courses ↔ Majors** (M:N): Each major has many courses and each course is part of the curriculum of many majors.
    - **Courses ↔ Courses** (M:N): Each course can requires one or more prerequisite courses.
    - **Students ↔ Sections** (M:N): Each student studies in many classes and each class has many students.

    ### Notes
    - All tables have a create time and an update time.
  |
}
